export default {
    MAINPAGEBUTTON: 'MAINPAGE_BUTTON',
    XBOXPAGEBUTTON: 'XBOXPAGE_BUTTON',
    COMPUTERPAGEBUTTON: 'COMPUTERPAGE_BUTTON',
    HANDHELDPAGEBUTTON: 'HANDHELD_BUTTON_SELECTED',
    PS4PAGEBUTTON: 'PS4PAGE_BUTTON',
    NINTENDOBUTTON: 'NINTENDO_BUTTON'
}