export default {
    RPGBUTTON: 'RPG_BUTTON',
    SHOOTERBUTTON: 'SHOOTER_BUTTON',
    SPORTSPAGEBUTTON: 'SPORTS_BUTTON',
    STRATEGYBUTTON: 'STRATEGY_BUTTON_SELECTED',
    ADVENTUREBUTTON: 'ADVENTURE_BUTTON',
    RACINGBUTTON: 'RACING_BUTTON',
    ALLGENRESBUTTON: 'ALLGENRES_BUTTON',
    
}